# Pin version
FROM golang:1.15.6-alpine3.13 as build

# Install system dependencies for the build
RUN apk add --no-cache \
    ca-certificates \
    git \
    make \
    bash

# Set the build environments
WORKDIR /go/src

# Install build dependencies
COPY Makefile ./
COPY go.mod go.sum ./
RUN make install

# Copy the project and run tests
COPY . ./
CMD make test

