# Pin version
FROM golang:1.14-alpine3.12 as build

# Install system dependencies for the build
RUN apk add --no-cache \
    ca-certificates \
    git \
    make

# Set the build environments
WORKDIR /go/src

# Install build dependencies
COPY Makefile ./
COPY go.mod go.sum ./
RUN make install

# Copy the project and run integration tests
COPY . ./
CMD make int-test

