name: authx-test

on:
  push:
    branches:
      - master

# All build/logic lives in the Makefile. This file just define the sequence.
jobs:
  build:  # Build includes linting and formatting. Doesn't create the binary (yet).
    runs-on:
      ubuntu-latest
    steps:
      - name: 'Check out project'
        uses: actions/checkout@v2
      - name: 'Set up Go'
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
      - name: 'Set up linter'
        uses: golangci/golangci-lint-action@v2
        with:
          version: 'v1.42'
      - name: 'Format Go files'
        run: make format
      - name: 'Lint Go files'
        run: make lint
  test:   # Run tests.
    runs-on:
      ubuntu-latest
    steps:
      - name: 'Check out project'
        uses: actions/checkout@v2
      - name: 'Set up Go'
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
      # Run unit tests.
      # NOTE: We can also run the unit tests as container by calling `make test-container`
      - name: 'Run unit tests'
        run: |
          ./scripts/start-db-container.sh | \
          make test
      - name: 'Run e2e web tests'
        run: make e2e-container
