name: authx-test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - name: 'Check out project'
        uses: actions/checkout@v2
      - name: 'Setup Go'
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
      # Install golangci-lint to the host instead of using golangci-lint-action
      # so that we can run `make lint`.
      - name: 'Install dev tools'
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
          sh -s -- -b $(go env GOPATH)/bin v1.35.2
      - name: 'Format Go files'
        run: make format
      - name: 'Lint Go files'
        run: make lint
  test:
    runs-on:
      ubuntu-latest
    steps:
      - name: 'Check out project'
        uses: actions/checkout@v2
      - name: 'Setup Go'
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
      - name: 'Run unit tests'
        run: make test
      - name: 'Run integration tests'
        run: make int-test-full
